name: Votemarket bounties
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute bounties.py # run bounties.py
        run: python bounties.py

      - name: execute analytics.ps # run analytics.py
        run: python analytics.py

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
