name: Votemarket bounties
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Every hours
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute bounties.py # run bounties.py
        run: python bounties.py

      - name: Commit and push changes to bribes repo
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Stake DAO Automation"
          git add .
          git commit -m "Add bounties"
          git pull --rebase
          git push origin main
        shell: bash
        if: always()
