name: Cake gauges
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 1-23 * * *' # every 15 min between 1h AM and 11 PM
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute cakeGauges.py
        run: python cakeGauges.py

      - name: execute sushiTokens.py
        run: python sushiTokens.py

      - name: execute cakeTvls.py
        run: python cakeTvls.py

      - name: Commit and push changes to bribes repo
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Stake DAO Automation"
          git add .
          git commit -m "Cake gauges"
          git pull --rebase
          git push origin main
        shell: bash
        if: always()
