name: Votemarket_XChain - Setting JSON of Block Header + hash (retrieved from Eth State Sender on latest period)
on:
  workflow_dispatch:
  schedule:
    - cron: '5 1 * * 4' # Every Thursday at 01:05 UTC

env:
  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
  ETHERSCAN_TOKEN: ${{ secrets.ETHERSCAN_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install toji
        run: cargo install --git https://github.com/rkdud007/toji --locked --force

      - name: execute header-data.py
        run: python bounties/x-chain/header-data.py

      - name: execute proofs.py
        run: python bounties/x-chain/proofs.py

      - name: Commit and push changes to bribes repo
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Stake DAO Automation"
          git add .
          git commit -m "Header update for latest period"
          git pull --rebase
          git push origin main
        shell: bash
        if: always()
